server:
  port: ${SERVER_PORT}

spring:
  security:
    oauth2:
      client:
        registration:
          oath0:
            client-id: ${OATH0_CLIENT_ID}
            client-secret: ${OATH0_CLIENT_SECRET}
            redirect-uri: ${OATH0_REDIRECT_URI}
            scope:
              - openid
              - profile
              - email
        provider:
          oath0:
            issuer-uri: ${OATH0_ISSUER_URI}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${DB_HIBERNATE_DDL_AUTO}
    show-sql: ${DB_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${DB_HIBERNATE_FORMAT_SQL}
management:
  endpoints:
    web:
      exposure:
        include: health

eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: ${EUREKA_CLIENT_INSTANCE_PREFER_IP_ADDRESS}
