server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${DB_HIBERNATE_DDL_AUTO}
    show-sql: ${DB_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${DB_HIBERNATE_FORMAT_SQL}
management:
  endpoints:
    web:
      exposure:
        include: health

eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: ${EUREKA_CLIENT_INSTANCE_PREFER_IP_ADDRESS}
# okta:
#   oauth2:
#     issuer: ${OKTA_ISSUER}
#     client-id: ${OKTA_CLIENT_ID}
#     client-secret: ${OKTA_CLIENT_SECRET}
#     scopes:
#       - openid
#       - profile
#       - email
