server:
  port: ${SERVER_PORT}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
      routes:
        - id: cloudinsight-user-service-auth
          uri: lb://cloudinsight-user-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RewriteLocationResponseHeader
              args:
                name: Location
                regexp: 'lb://cloudinsight-user-service/(?<segment>.*)'
                replacement: 'http://localhost:8080/${segment}'
                stripVersion: AS_IN_REQUEST
        - id: cloudinsight-user-service-oauth2-login
          uri: lb://cloudinsight-user-service
          predicates:
            - Path=/oauth2/authorization/**
        - id: cloudinsight-user-service-oauth2-redirect
          uri: lb://cloudinsight-user-service
          predicates:
            - Path=/login/oauth2/code/**
        - id: cloudinsight-user-service-user-apis
          uri: lb://cloudinsight-user-service
          predicates:
            - Path=/api/v1/users/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
  instance:
    prefer-ip-address: ${EUREKA_CLIENT_INSTANCE_PREFER_IP_ADDRESS}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
