server:
  port: ${SERVER_PORT}

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - http://localhost:3001
              - https://dev.cloudinsightpro.com
              - https://cloudinsight-frontend-rw.vercel.app
              - https://cloudinsight-frontend-rw-v2.vercel.app
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            # This is the fix: specifying allowed headers instead of using the wildcard.
            allowedHeaders:
              - Content-Type
              - X-Requested-With
              - Accept
              - Origin
              - Access-Control-Request-Method
              - Access-Control-Request-Headers
              - Authorization
            allowCredentials: true
      routes:
        - id: cloudinsight-user-service-auth
          uri: lb://cloudinsight-user-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: RewriteLocationResponseHeader
              args:
                name: Location
                regexp: 'lb://cloudinsight-user-service/(?<segment>.*)'
                replacement: 'https://api-dev.cloudinsightpro.com/${segment}'
                stripVersion: AS_IN_REQUEST
        - id: cloudinsight-user-service-oauth2-login
          uri: lb://cloudinsight-user-service
          predicates:
            - Path=/oauth2/authorization/**
        - id: cloudinsight-user-service-oauth2-redirect
          uri: lb://cloudinsight-user-service
          predicates:
            - Path=/login/oauth2/code/**
        - id: cloudinsight-user-service-user-apis
          uri: lb://cloudinsight-user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: RewriteLocationResponseHeader
              args:
                name: Location
                regexp: 'lb://cloudinsight-user-service/(?<segment>.*)'
                replacement: 'https://api-dev.cloudinsightpro.com/${segment}'
                stripVersion: AS_IN_REQUEST
        - id: cloudinsight-costs-service
          uri: lb://cloudinsight-costs-service
          predicates:
            - Path=/api/v1/costs/**
        - id: cloudinsight-costs-service-cost-injection
          uri: lb://cloudinsight-costs-service
          predicates:
            - Path=/api/v1/ingestion/trigger/**
        - id: cloudinsight-costs-service-cost-injection
          uri: lb://cloudinsight-costs-service
          predicates:
            - Path=/api/v1/cost-centers/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
  instance:
    prefer-ip-address: ${EUREKA_CLIENT_INSTANCE_PREFER_IP_ADDRESS}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
