server:
  port: ${SERVER_PORT}

# MongoDB Configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer-group: cloudinsight-anomaly-group
    topic-cost: cost.daily.metrics
    topic-anomaly: anomaly.detected
  model:
    base-path: ./models
    default-filename: isolation_forest.model
    trees: 100
    sample-size: 256
    threshold: 0.75
    window-days: 90
    retrain-days: 7
  storage:
    serialize-format: java-serialization
  executor:
    thread-pool-size: 4

# Management & Health
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: ${EUREKA_CLIENT_INSTANCE_PREFER_IP_ADDRESS}

