server:
  port: ${SERVER_PORT}

spring:
  cloud:
    gateway:
      routes:
        - id: cloudinsight-user-service
          uri: lb://cloudinsight-user-service
          predicates:
            - Path=/api/v1/auth/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
  instance:
    prefer-ip-address: ${EUREKA_CLIENT_INSTANCE_PREFER_IP_ADDRESS}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
